-- MySQL Script generated by MySQL Workbench
-- Wed May 29 15:37:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project2` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `project2` ;

-- -----------------------------------------------------
-- Table `project2`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`member` (
  `username` VARCHAR(24) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `id_card` VARCHAR(13) NOT NULL,
  `id_line` VARCHAR(24) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(24) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  `type_user` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `UK_mbmcqelty0fbrvxp1q58dn57t` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_chhad6vlkaqsaqe4a1p845kia` (`id_card` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`officer` (
  `position` VARCHAR(100) NOT NULL,
  `username` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `FK9q10vmj5clpaddwt27tj3a778`
    FOREIGN KEY (`username`)
    REFERENCES `project2`.`member` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`type_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`type_project` (
  `name_type_project` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`name_type_project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`project` (
  `id_project` INT(11) NOT NULL AUTO_INCREMENT,
  `budget` DOUBLE NOT NULL,
  `date_start_project` DATETIME NOT NULL,
  `duration_year` INT(11) NOT NULL,
  `name_project` VARCHAR(255) NOT NULL,
  `status_project` VARCHAR(24) NOT NULL,
  `username` VARCHAR(24) NOT NULL,
  `id_type_project` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_project`),
  UNIQUE INDEX `UK_jkxhhrh8713xponlmhp9w0chk` (`name_project` ASC) VISIBLE,
  INDEX `FKjq22xkc82m51to5chqtwqtsrd` (`username` ASC) VISIBLE,
  INDEX `FKlxp7cksmb5tl4d8h1srnuu9f4` (`id_type_project` ASC) VISIBLE,
  CONSTRAINT `FKjq22xkc82m51to5chqtwqtsrd`
    FOREIGN KEY (`username`)
    REFERENCES `project2`.`officer` (`username`),
  CONSTRAINT `FKlxp7cksmb5tl4d8h1srnuu9f4`
    FOREIGN KEY (`id_type_project`)
    REFERENCES `project2`.`type_project` (`name_type_project`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`period` (
  `id_period` INT(11) NOT NULL AUTO_INCREMENT,
  `budget_period` DOUBLE NOT NULL,
  `end_period` DATETIME NOT NULL,
  `no_period` INT(11) NOT NULL,
  `start_period` DATETIME NOT NULL,
  `id_project` INT(11) NOT NULL,
  PRIMARY KEY (`id_period`),
  INDEX `FKpqyvvixij21y5leja5b6vu4d3` (`id_project` ASC) VISIBLE,
  CONSTRAINT `FKpqyvvixij21y5leja5b6vu4d3`
    FOREIGN KEY (`id_project`)
    REFERENCES `project2`.`project` (`id_project`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`item` (
  `id_item` VARCHAR(24) NOT NULL,
  `budget_item` DOUBLE NOT NULL,
  `date_book` DATETIME NOT NULL,
  `detail` TEXT NOT NULL,
  `end_item` DATETIME NOT NULL,
  `start_item` DATETIME NOT NULL,
  `title_item` VARCHAR(100) NOT NULL,
  `id_period` INT(11) NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `FKlb6ha7nkhy7dqu73qajnhbp47` (`id_period` ASC) VISIBLE,
  CONSTRAINT `FKlb6ha7nkhy7dqu73qajnhbp47`
    FOREIGN KEY (`id_period`)
    REFERENCES `project2`.`period` (`id_period`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`file_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`file_item` (
  `file_name` VARCHAR(255) NOT NULL,
  `id_item` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`file_name`),
  INDEX `FKgsx1ic53kdjucobosgwvi1e81` (`id_item` ASC) VISIBLE,
  CONSTRAINT `FKgsx1ic53kdjucobosgwvi1e81`
    FOREIGN KEY (`id_item`)
    REFERENCES `project2`.`item` (`id_item`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`file_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`file_project` (
  `name_file_project` VARCHAR(255) NOT NULL,
  `id_project` INT(11) NOT NULL,
  PRIMARY KEY (`name_file_project`),
  INDEX `FK4hclkppfxdayika10x2g5dtj7` (`id_project` ASC) VISIBLE,
  CONSTRAINT `FK4hclkppfxdayika10x2g5dtj7`
    FOREIGN KEY (`id_project`)
    REFERENCES `project2`.`project` (`id_project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`researcher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`researcher` (
  `faculty` VARCHAR(100) NOT NULL,
  `major` VARCHAR(100) NOT NULL,
  `username` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `FK598xsg0f5nvvplglwsku1igrm`
    FOREIGN KEY (`username`)
    REFERENCES `project2`.`member` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `project2`.`researcher_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project2`.`researcher_project` (
  `status_research` VARCHAR(20) NOT NULL,
  `project_id_project` INT(11) NOT NULL,
  `researcher_username` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`project_id_project`, `researcher_username`),
  INDEX `FKceccsu7v5i7xobhlab39j6xn` (`researcher_username` ASC) VISIBLE,
  CONSTRAINT `FKceccsu7v5i7xobhlab39j6xn`
    FOREIGN KEY (`researcher_username`)
    REFERENCES `project2`.`researcher` (`username`),
  CONSTRAINT `FKduo5mugwymow5s6m7vaxsqh61`
    FOREIGN KEY (`project_id_project`)
    REFERENCES `project2`.`project` (`id_project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
